# This workflow will build, test, and optionally publish a .NET project
name: .NET CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          # Optional: Enable caching of NuGet packages
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: Restore Dependencies
        run: dotnet restore
        # If using lock file, enable this line for reproducible builds
        # run: dotnet restore --use-lock-file

      - name: Build Project
        run: dotnet build --configuration Release --no-restore

      - name: Run Unit Tests
        run: dotnet test --no-build --verbosity normal --logger "console;verbosity=detailed"
        
      - name: Publish Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            **/TestResults/*.xml
            **/TestResults/*.trx
        # Optional: Add more paths if needed

      - name: Upload Build Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: built-app
          path: |
            ./HabitTrackerApp/bin/Release/
